### PR TITLE
Update docs with latest installation/setup info

### PR DESCRIPTION
**Pull request by andrew-nowak**
## What does this change?

Add instructions for installing from Guardian's homebrew tap, and how to set up new configurations/profiles.

### CODE REVIEW

**Review by paperboyo — APPROVED** [review]
Thank you for this! Successfully using latest via brew. I guess the bit about weird (to me) `dev-` is at linked address?

**Comment by andrew-nowak** [comment]
yep, I'm also about to improve those docs too

**Comment by ParisaTork** [comment]
This is fab - it would also be awesome to add some troubleshooting steps for homebrew

**Review by ParisaTork — APPROVED** [review]

**Comment by ParisaTork** [comment]
Worth noting that in the 'add an API key' section, we had issues with Grid-CLI recognising the AWS region, so we opted to use the AWS GUI instead.

**Comment by andrew-nowak** [comment]
thanks @ParisaTork 
the little struggle we had with homebrew was due to the grid-cli not being fully added. This is now complete in guardian/homebrew-devtools#83 so such problems won't surface for future users.
The PR in the guardian/grid#3892 to update API key docs also contains a fix for that script to set a region for AWS, so that problem also shouldn't surface again.

**Pull request merged**
